apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-02
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    path: 03-argocd-instances/pacman-02
    repoURL: https://github.com/marrober/argocd-app-in-namespace
    targetRevision: main
  project: app-in-namespace-root
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:  
    - Validate=true 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s
